import { test } from "node:test";
import assert from "node:assert/strict";
import { importALoTiA } from "../src/alotia-import.js";

test("imports physical ALoTiA JSON, converts units, material data and loads", () => {
  const data = {
    format: "aLOTofImaginArches/state",
    version: 1,
    system: "kgcm",
    model: {
      frame: { coordinates: "physical" },
      blocks: [{ x: [0, 100, 100, 0], y: [0, 0, 50, 50] }],
      groups: [{ id: 7, color: "#123456" }],
      blockGroups: [7],
      areas: [5000],
      thickness: [20],
      weights: [200],
    },
    forces: { points: [[50, 50]], x: [3], magnitudes: [10] },
  };
  const got = importALoTiA(JSON.stringify(data), { fileName: "arch.json" });
  assert.equal(got.particles.length, 1);
  assert.equal(got.particles[0].color, "#123456");
  assert.ok(Math.abs(got.particles[0].x - 0.5) < 1e-12);
  assert.ok(Math.abs(got.particles[0].y - 0.25) < 1e-12);
  assert.ok(Math.abs(got.particles[0].load - 98.0665) < 1e-9);
  assert.ok(Math.abs(got.particles[0].loadX - 29.41995) < 1e-9);
  assert.ok(Math.abs(got.thickness - 0.2) < 1e-12);
  assert.ok(got.materialDensity > 1900 && got.materialDensity < 2100);
});

test("rejects unscaled ALoTiA JSON", () => {
  const data = {
    format: "aLOTofImaginArches/state",
    version: 1,
    system: "SI",
    model: {
      frame: { coordinates: "pixels" },
      blocks: [{ x: [0, 1, 0], y: [0, 0, 1] }],
    },
  };
  assert.throws(() => importALoTiA(JSON.stringify(data)), /Scale the model/);
});

test("reconstructs an ALoTiA INP block boundary from its mesh", () => {
  const inp = `*Heading
** Generated by aLoTiA. Units follow the active model unit system.
*Part, name=BLOCK_1
*Node
1, 0, -0.1, 0
2, 1000, -0.1, 0
3, 1000, -0.1, 500
4, 0, -0.1, 500
5, 0, 0.1, 0
6, 1000, 0.1, 0
7, 1000, 0.1, 500
8, 0, 0.1, 500
9, 500, -0.1, 0
10, 500, -0.1, 500
11, 500, 0.1, 0
12, 500, 0.1, 500
*Element, type=C3D8
1, 1, 9, 10, 4, 5, 11, 12, 8
2, 9, 2, 3, 10, 11, 6, 7, 12
*End Part
`;
  const got = importALoTiA(inp, { fileName: "arch.inp", inpLengthUnit: "mm" });
  assert.equal(got.particles.length, 1);
  assert.ok(Math.abs(got.particles[0].x - 0.5) < 1e-12);
  assert.ok(Math.abs(got.particles[0].y - 0.25) < 1e-12);
  assert.equal(got.particles[0].vertices.length, 8);
  assert.equal(got.bounds.bottom, 0);
});

test("rejects generic Abaqus decks", () => {
  assert.throws(
    () => importALoTiA("*Heading\n*Part, name=X", { fileName: "x.inp" }),
    /not produced by ALoTiA/,
  );
});
